"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l9%j*9zz^x(sn_gtb7lo5&_noe43gv7-wcgneakupl4&7)1b#^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'backendfinalspeitel.onrender.com',
    'localhost',
    '127.0.0.1',
    '192.168.8.103',
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'media_tracker',
    'rest_framework',
    
    # --- AUTHENTICATION APPS ---
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ---------------------------
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # MUST be first for CORS
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this for static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # REQUIRED BY django-allauth
    'allauth.account.middleware.AccountMiddleware', 
    
    'django.middleware.common.CommonMiddleware',
    # Disable CSRF for API endpoints - Token Auth is used instead
    'config.middleware.DisableCSRFForAPIMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# --- 🛑 EDIT 1: REMOVE PASSWORD RESTRICTIONS (Django Core) ---
AUTH_PASSWORD_VALIDATORS = [
    # Removed all default validators to allow any password.
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True

# --- NEW AUTH CONFIGURATION ---
SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Uses token for mobile/API access
        'rest_framework.authentication.TokenAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Ensures that most endpoints require a logged-in user, but allows read-only for public views
        'rest_framework.permissions.IsAuthenticatedOrReadOnly', 
    )
}

# --- 🛑 EDIT 2: DJ-REST-AUTH CONFIGURATION (CRITICAL) ---
REST_AUTH = {
    # Ensures the JSON body from the frontend is processed correctly
    'USE_JSON_AS_CONTENT_TYPE': True, 
    
    # 💥 CRITICAL CHANGE: Use the custom serializer you defined in media_tracker/serializers.py
    'REGISTER_SERIALIZER': 'media_tracker.serializers.CustomRegisterSerializer',
    
    # Auto-generate token for new users
    'SESSION_LOGIN': False,
}

# --- 🛑 EDIT 3: DJANGO ALLAUTH ACCOUNT SETTINGS (Removes final validations) ---
# Disables minimum password length enforced by allauth
ACCOUNT_PASSWORD_MIN_LENGTH = 1 
# Set authentication method to username/password (required for API setup)
ACCOUNT_AUTHENTICATION_METHOD = 'username'
# Do not require an email address (optional, but helpful for testing)
ACCOUNT_EMAIL_REQUIRED = False
# Do not require email verification
ACCOUNT_EMAIL_VERIFICATION = 'none'
# Use username for signup
ACCOUNT_USERNAME_REQUIRED = True


# 💥 🛑 EDIT 4: CSRF EXEMPTION FIX (Fixes generic 400 error from mobile app)
# Whitelist the IP address where the frontend is running/requesting from
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.8.103:8000',
    'http://192.168.254.150:8000',
    'http://localhost:8000'
]
# Exempt all URLs starting with /api/ from the standard CSRF check
CSRF_EXEMPT_PATHS = ['/api/']