# Generated by Django 6.0 on 2025-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series'), ('Book', 'Book')], max_length=10)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
