# Generated by Django 6.0 on 2025-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
