# Generated by Django 5.2.9 on 2025-12-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_tracker', '0002_mediaitem_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-added_date']},
        ),
        migrations.RenameField(
            model_name='mediaitem',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='estimated_time_hours',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('To Watch', 'To Watch'), ('Finished', 'Finished'), ('Trash', 'Trash')], default='To Watch', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='time_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show'), ('Book', 'Book')], default='Movie', max_length=10),
        ),
    ]
