# Generated by Django 5.2.9 on 2025-12-10 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_tracker', '0003_alter_mediaitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-is_favorite', 'title']},
        ),
        migrations.RenameField(
            model_name='mediaitem',
            old_name='added_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show'), ('Book', 'Book'), ('Game', 'Video Game')], default='Movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned to Watch'), ('Watching', 'Currently Watching'), ('Finished', 'Finished')], default='Planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
